export class Register{
	 UserId:number; 
	loginEmailId:string;
	Password:string;
	FirstName:string;
	LastName:string;
	 PhoneNo:string;
	Address:string;
	City:string;
	StateId:number;
	CountryId:number;
	ZipCode:string;
	OfficeLocation:string;
	ProfileImageUrl:string;
	Fax:string;
	AccountManagerId:number;
	CustomerId:number;
	AccountOwner:string;
	ModifiedBy:string;
	CreatedBy:string;
	Option:string; 
}